### PR TITLE
Validators correctly raise exceptions

### LINKED ISSUE #445: Validators do not raise IndexError when it catches a ValueError
Hi. When a validator accidentally raises a ZeroDivisionError, the is correctly raised, but when a validator accidentally raises a ValueError, an IndexError is raised instead. This makes the debugging a bit more difficult.

Here is a script to reproduce the problem:

```python
import wtforms
import werkzeug


def division_error_validator(form, field): raise ZeroDivisionError
class DivisionErrorForm(wtforms.Form):
    foo = wtforms.StringField(validators=[division_error_validator])

def value_error_validator(form, field): raise ValueError
class ValueErrorForm(wtforms.Form):
    foo = wtforms.StringField(validators=[value_error_validator])


try:
    DivisionErrorForm(werkzeug.ImmutableMultiDict({"bar": "baz"})).validate()
except ZeroDivisionError:
    print("ZeroDivisionError OK")
except Exception as exc:
    print("ZeroDivisionError KO - found %s" % type(exc))

try:
    ValueErrorForm(werkzeug.ImmutableMultiDict({"bar": "baz"})).validate()
except ValueError:
    print("ValueError OK")
except Exception as exc:
    print("ValueError KO - found %s" % type(exc))

# prints
# ZeroDivisionError OK
# ValueError KO - found <type 'exceptions.IndexError'>
```

### PR DESCRIPTION
**Pull request by azmeuk**
This PR should fix #445 
Because `ValidationError` inherits from `ValueError`, A `ValueError` raised inside a validator is just considered as the validator refusing the data. This behavior felt unexpected to me, and is fixed in this PR.

Here is the piece of code from #445 illustrating the bug:

```python
>>> from wtforms import StringField, Form
>>> from werkzeug.datastructures import MultiDict
...
>>> def division_error_validator(form, field): raise ZeroDivisionError
>>> class DivisionErrorForm(Form):
...     foo = StringField(validators=[division_error_validator])
...
>>> def value_error_validator(form, field): raise ValueError
>>> class ValueErrorForm(Form):
...    foo = StringField(validators=[value_error_validator])
...
>>> DivisionErrorForm(MultiDict({"bar": "baz"})).validate()
Traceback (most recent call last):
...
ZeroDivisionError

>>> ValueErrorForm(MultiDict({"bar": "baz"})).validate()
Traceback (most recent call last):
  File "/home/azmeuk/dev/wtforms/src/wtforms/fields/core.py", line 275, in _run_validation_chain
    validator(form, self)
  File "<stdin>", line 1, in value_error_validator
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/azmeuk/dev/wtforms/src/wtforms/form.py", line 300, in validate
    return super(Form, self).validate(extra)
  File "/home/azmeuk/dev/wtforms/src/wtforms/form.py", line 136, in validate
    if not field.validate(self, extra):
  File "/home/azmeuk/dev/wtforms/src/wtforms/fields/core.py", line 255, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/azmeuk/dev/wtforms/src/wtforms/fields/core.py", line 281, in _run_validation_chain
    self.errors.append(e.args[0])
IndexError: tuple index out of range
```

### CODE REVIEW

**Comment by davidism** [comment]
#61 is related

**Comment by davidism** [comment]
I'm not 100% sure on this one, I feel like there was a reason `ValueError` was accepted in certain places. Are there previous discussions about this?

**Comment by azmeuk** [comment]
[A comment](https://github.com/wtforms/wtforms/issues/61#issuecomment-48127548) on the thread you mentioned, says that during the processing phase, `ValidationError` are unrelevant, so only `ValueError` are handled.

But I am not sure this is directly related to this patch, because this line it changes to `except ValidationError`, is in `_run_validation_chain`, so basically in the validation phase.
https://github.com/wtforms/wtforms/blob/129040ab4d5af83a05ddc7b63f854d48be3d55aa/src/wtforms/fields/core.py#L280

My feeling is that we should trigger special wtforms actions (such as making the validation fail (i.e. return `False`)) on wtforms exceptions, and let the other exception types reach the user so they can be debugged.
Currently, there is no way to differentiate a `ValueError` that is raised to make the validation fail and a *classical* `ValueError`.

**Comment by azmeuk** [comment]
Thank you. I think I won't backport this one.

**Pull request merged**
