### PR TITLE
Support for TimeField

### PR DESCRIPTION
**Pull request by lipis**
Even though the `TimeInput` was there the `TimeField` was missing..

### CODE REVIEW

**Comment by lipis** [comment]
@crast can we have this one?! 

p.s. I'm not sure how to fix the coverage though

**Comment by roganov** [comment]
To fix the coverage issue you need to add tests (see [tests for DateField](https://github.com/wtforms/wtforms/blob/master/tests/fields.py#L532)).

**Comment by lipis** [comment]
@roganov @crast It's all green now :)

**Comment by lipis** [comment]
@crast Any luck with this one?

**Comment by lipis** [comment]
@davidism @crast Can we do something about this one?!

**Comment by topless** [comment]
That one actually could be helpful.

**Comment by lipis** [comment]
Is there anybody out there?

**Comment by lipis** [comment]
Anything new on this one?!

**Comment by topless** [comment]
Can we get that in?

**Comment by lipis** [comment]
Wohoo.. and now a release :) thank you..

**Comment by lipis** [comment]
So any chance for release soon! :)

**Comment by lipis** [comment]
Any new release with this fix?

**Comment by lipis** [comment]
Hey... will we have any release with this feature any time soon?!

**Pull request merged**
