### PR TITLE
Backported fixes from branch master to branch 2.2-maintenance

### PR DESCRIPTION
**Pull request by azmeuk**
As it was discussed on the discord, I listed the fixes that are present in the master branch and can safely be backported to branch 2.2-maintenance so we could hopefully cut a new 2.* release.

You can see the list of backports in the commit log.

I did not backport:
- #451, #493, #526 because they are more features than bugfixes
- #484, #423, #424, #420, #418, #415, #422 because they are more refactoring than bugfixes
- #409 because it is just about documentation of HTML5 fields
- #430 because I do not understand the need for babel > 2.6.0
- #400, #403, #375, #429 because they require new dependencies (ipaddress and markupsafe)
- #355 because of [this comment](https://github.com/wtforms/wtforms/issues/291#issuecomment-395584334)

I did backport #389 but I am not totally confident because of this docstring:
https://github.com/wtforms/wtforms/blob/df892b87365f4a62cab33c98f49ed84660bd18e6/src/wtforms/widgets/core.py#L49-L54

### CODE REVIEW

**Comment by davidism** [comment]
I think some of the PRs you didn't backport are appropriate for a 2.3 release. Anything that doesn't break existing behavior and just adds a feature is fine.

- #451
- #493
- #526
- #409 probably unless it's not relevant to 2.x
- #400
- #403
- #375
- #429

**Comment by azmeuk** [comment]
Done.

**Comment by davidism** [comment]
I'm not going to review this since it's just backports of things we already merged. Changelog looks good. Not sure if you're keeping this open for more backports, but it's good to go whenever you're ready.

**Comment by azmeuk** [comment]
Yep, no need to review in details. I am confident with the backports being accurate. This was just about knowing what to backport or not.

**Comment by Jason-Crowe** [comment]
don't think you realized that you have backported a change (#400) that specifically says it is not backwards compatible and this broke airflow 1.10.10 setups

**Comment by kaxil** [comment]
@azmeuk Is it possible to restore `HTMLString` and cut `2.3.1` since it specifically said it was a backwards incompatible change in the PR?

**Comment by azmeuk** [comment]
@kaxil I cannot do it myself but hopefully another maintainer will take care of it soon :)

**Comment by kaxil** [comment]
> @kaxil I cannot cut a release myself but hopefully another maintainer will take care of it soon :)

Thanks 🤞

**Pull request merged**
