### PR TITLE
New logo

### LINKED ISSUE #569: Rework the WTForms logo
We have this logo for the wtforms group:

logo

And we have this logo for the documentation:

logo

Both are in poor resolution. We should probably make them svgs.

Any suggestions or help is welcomed!

### PR DESCRIPTION
**Pull request by azmeuk**
Integration of the new logo by @funelie
Fixes #569

### CODE REVIEW

**Comment by davidism** [comment]
Do `git commit --amend --author "name <email>"` to set the author to @funelie's preferred name and email.

**Comment by azmeuk** [comment]
Done.

**Comment by davidism** [comment]
I'd call them `logo_joined.svg`, `logo_split.svg`, and `logo_square.svg` instead, just to make the names clearer. (Also "split" instead of "splitted" sounds more correct to me.)

**Review by davidism — APPROVED** [review]

**Comment by azmeuk** [comment]
Thanks a lot @funelie!

**Pull request merged**
