### PR TITLE
Feature proposal: Partial object updates

### PR DESCRIPTION
**Pull request by codebynumbers**
I often find myself wanting to use wtforms to populate an object for PUT operations. However the current behavior of populate_obj() essentially clobbers all model properties if even if they were not intended to be changed. This would allow the use of wtforms to validate fields and partially apply them to an object.

### CODE REVIEW

**Comment by hnb2** [comment]
I am looking forward to see this PR merged, it will allow the use of patched data. And it will solve this ticket too I guess: https://github.com/wtforms/wtforms/issues/109

**Comment by crast** [comment]
I'm shelving this as far future

**Comment by debrice** [comment]
Does this also addresses the case where a field value would be required but not provided:
For example, a title field could be required only when provided, the form wouldn't fail if the "title" was not a part of `BaseForm._formkeys`

**Comment by davidism** [comment]
It looks like this doesn't account for validation. It also can't account for nested fields, which the other PR had an issue with too.

POST and PUT both have the expectation that the full resource is sent. PATCH does not, but also implies a more sophisticated algorithm than implemented here.

I recognize that support for PATCH requests would be useful, but I think we need to do some more design work on this still.

**Pull request closed without merging**
