### PR TITLE
ColorField implementation

### PR DESCRIPTION
**Pull request by PanderMusubi**
Describe the issue you are attempting to fix.

Implement support for ColorField

Link to any relevant issues or pull requests.

https://github.com/wtforms/wtforms/issues/725

Describe what this patch does to fix the issue.

Implements it

### CODE REVIEW

**Comment by PanderMusubi** [comment]
@azmeuk would you like to review this PR please? Thanks.

**Comment by azmeuk** [comment]
Hello. Sorry for my silence I do not have much time to spend on wtforms these days. I will try to look a this this week.

**Comment by PanderMusubi** [comment]
@azmeuk friendly reminder to move this one forward.

**Comment by azmeuk** [comment]
Looks good to me.

**Pull request merged**
