### PR TITLE
hungarian localisation

### PR DESCRIPTION
**Pull request by magwas**

### CODE REVIEW

**Comment by magwas** [comment]
Any news on this?

**Comment by magwas** [comment]
Any news?

**Comment by magwas** [comment]
?

**Comment by magwas** [comment]
?

**Comment by magwas** [comment]
?

**Comment by magwas** [comment]
?

**Comment by magwas** [comment]
Could you take a look at this?

**Comment by magwas** [comment]
@crast please take a look at it

**Comment by magwas** [comment]
could you please answer at least?

**Comment by davidism** [comment]
I'm aware of this as well as the other Hungarian translation in #262.  I asked a friend who speaks Hungarian to look over both, they said:

> the two translations are almost equally valid, and both are lacking a few commas in my opinion. Anyway, I'm leaning a bit towards 262, it's a bit more specific in a few places. But watch out for line 99: the field specifier is missing from the end of the translation. And "not a valid float" is translated into "not a valid fraction", which is bugging me a bit (line 169 in the other translation is precise)

Since the other PR came first and it has an external vote of approval I'm more inclined to merge that one assuming the two things mentioned get fixed.  Could you give yours another look over and compare notes with #262?

**Comment by davidism** [comment]
Merged #262, so closing this one.  Thanks for your interest though, it's appreciated!  If you want to make further improvements, more PRs are welcome.

**Pull request closed without merging**
